headwire-edge-delivery/eds-self-service-website

- blocks/dashboard/dashboard.js
- blocks/site-details/site-details.js
- icons/remove-circle.svg
- scripts/scripts.js
- styles/styles.css
Added UI for sharing project with single emails or entire domains.
Added UI to change the contact email where submissions of the content form are sent to (in blocks sections)
> Share and contact

- blocks/site-details/site-details.css
- blocks/site-details/site-details.js
> css variables saving

- blocks/wizard/wizard.css
- blocks/wizard/wizard.js
- icons/chevron-down.svg
- styles/styles.css
Added next/prev buttons to template selector to more clearly indicate that more templates exist
> added buttons to template picker

- blocks/site-details/site-details.js
- scripts/auth0.js
redirect to dashboard if user is authenticated and not referred from our site
added favicon img to favicon menu
> Home redirect

- blocks/site-details/site-details.css
- blocks/site-details/site-details.js
- styles/styles.css
displaying screenshots from a blocks authoring guide in the blocks dialog
> block screenshots in block dialog

- blocks/site-details/site-details.css
- blocks/site-details/site-details.js
Getting drive id from admin.hlx.page/status
> Edit link on Pages

- .eslintrc.js
- blocks/theme-editor/contrast-worker.js
- blocks/theme-editor/theme-editor.css
- blocks/theme-editor/theme-editor.js
Had to make a new branch, it ended up being easier to just port my changes then to fix all the merge conflicts.
We need to keep an eye on if the chrome tab crashes. I wanted to add a debounce to the editor onChange, but it would use an outdated state and I could not figure out why.
Test URLs:
- Before: https://main--eds-self-service-website--headwire-edge-delivery.hlx.live/theme/club
- After: https://contrast--eds-self-service-website--headwire-edge-delivery.hlx.live/theme/club
> Contrast Checker

- blocks/theme-editor/contrast-worker.js
- blocks/theme-editor/theme-editor.js
Test URLs:
- Before: https://main--eds-self-service-website--headwire-edge-delivery.hlx.live/
- After: https://footercontrast--eds-self-service-website--headwire-edge-delivery.hlx.live/
> Extra Footer Section

- blocks/site-details/site-details.css
- blocks/site-details/site-details.js
- tour/email.js
- tour/index.js
- tour/main.js
Test URLs:
- Before: https://main--eds-self-service-website--headwire-edge-delivery.hlx.live/
- After: https://canalytics--eds-self-service-website--headwire-edge-delivery.hlx.live/
> fix campaign analytics

- tour/settings.js
Test URLs:
- Before: https://main--eds-self-service-website--headwire-edge-delivery.hlx.live/
- After: https://tourbugs--eds-self-service-website--headwire-edge-delivery.hlx.live/
> Small Tour Fix for Update Status

- blocks/theme-editor/theme-editor.js
- tour/main.js
Test URLs:
- Before: https://main--eds-self-service-website--headwire-edge-delivery.hlx.live/
- After: https://<branch>--eds-self-service-website--headwire-edge-delivery.hlx.live/
> Updated Help Button enabling

- blocks/account-settings/account-settings.js
- blocks/dashboard/dashboard.js
- blocks/site-details/site-details.js
- tour/main.js
Alternate delete-all-projects dialog when user has no projects.
Optional chaining for some failed requests, no longer gives appearance of loading forever.
Client side campaign name validation.
Fixes: #43 & #46
> Minor fixes

- blocks/site-details/site-details.js
catching fetches so error messages show up correctly, and don't leave users in infinite loading dialogs
> catching fetches

- blocks/email-composer/email-composer.js
- blocks/site-details/site-details.css
- blocks/site-details/site-details.js
- blocks/theme-editor/theme-editor.js
- blocks/wizard/wizard.css
- tour/email.js
- tour/site.js
> use realtime index and fix email styles path

- blocks/site-details/site-details.css
- blocks/site-details/site-details.js
- tour/main.js
added preview and live links for site-details.
Test was failing because it looked for live URL, I added & am not testing for both
> added preview and live links for site-details.

- blocks/site-details/site-details.js
> check email name if it already exists

- blocks/dashboard/dashboard.js
- tour/helpButton.js
- tour/main.js
Test URLs:
- After: https://tourtestfix--eds-self-service-website--headwire-edge-delivery.aem.live/
> Small changes for the Tour Tests

- scripts/scripts.js
> updated script api url

- blocks/theme-editor/contrast-worker.js
- blocks/theme-editor/theme-editor.js
- Club: https://github.com/headwire-self-service-templates/club-template/pull/41
- Sports: https://github.com/headwire-self-service-templates/sports-template/pull/28
- WKND: https://github.com/headwire-self-service-templates/wknd-template/pull/41
Last part of https://github.com/headwire-self-service-templates/sports-template/issues/24
Test URLs:
- After: https://theme-inputs--eds-self-service-website--headwire-edge-delivery.aem.live/
> input color inputs

- blocks/dashboard/dashboard.css
- blocks/dashboard/dashboard.js
Test URLs:
- After: https://project-thumbnail--eds-self-service-website--headwire-edge-delivery.aem.live/
> project thumbnail

- blocks/email-composer/email-composer.js
Fix #82 
Test URLs:
- After: https://fix-recipients--eds-self-service-website--headwire-edge-delivery.aem.live/
> fix recipients addition and removal

- blocks/account-settings/account-settings.css
- blocks/dashboard/renderSiteList.js
- blocks/site-details/renderSiteOverview.js
- blocks/site-details/site-details.css
- scripts/scripts.js
- styles/styles.css
Fix #85
Test URLs:
- After: https://thumbnail--eds-self-service-website--headwire-edge-delivery.aem.live/
> add project thumbnail to site overview

- blocks/dashboard/dashboard.css
Test URLs:
- After: https://<branch>--eds-self-service-website--headwire-edge-delivery.aem.live/
> Table enhancement

- blocks/dashboard/dashboard.css
Test URLs:
- After: https://<branch>--eds-self-service-website--headwire-edge-delivery.aem.live/
> Fix table mobile

- blocks/site-details/renderCampaignsAnalytics.js
- blocks/site-details/renderCampaignsOverview.js
- blocks/site-details/renderSiteOverview.js
- blocks/site-details/renderSitePages.js
- blocks/site-details/site-details.css
- styles/styles.css
Fix #87 
Test URLs:
- After: https://de--eds-self-service-website--headwire-edge-delivery.aem.live/
> delete email feat

- blocks/dashboard/dashboard.css
- blocks/dashboard/renderAdmin.js
- blocks/dashboard/renderSiteList.js
- blocks/site-details/renderCampaignsAnalytics.js
- blocks/site-details/site-details.css
- head.html
- libs/clusterize/clusterize.css
- libs/clusterize/clusterize.js
- libs/pagination/pagination.css
- libs/pagination/pagination.js
- libs/queryParams/queryParams.js
- scripts/scripts.js
- styles/styles.css
Reverts headwire-edge-delivery/eds-self-service-website#106
> Revert "Revert "Pagination""

- blocks/email-composer/email-composer.js
- blocks/site-details/renderCampaignsOverview.js
- blocks/site-details/renderSitePages.js
- blocks/theme-editor/theme-editor.js
Fix #108 
Test URLs:
- After: https://nf--eds-self-service-website--headwire-edge-delivery.aem.live/
> no newsletter fix

- blocks/dashboard/dashboard.css
- blocks/email-composer/email-composer.js
- blocks/footer/footer.css
- blocks/site-details/renderCampaignsAudience.js
- blocks/site-details/renderSitePages.js
- blocks/site-details/site-details.css
- blocks/site-details/site-details.js
- libs/pagination/pagination.css
- scripts/analytics.js
- styles/analytics.css
- styles/styles.css
- tour/site.js
Fix #110 
Test URLs:
- After: https://status--eds-self-service-website--headwire-edge-delivery.aem.live/
> add published status

- .eslintrc.js
- blocks/dashboard/dashboard.css
- blocks/dashboard/renderAccount.js
- blocks/dashboard/renderAdmin.js
- blocks/site-details/renderCampaignsAnalytics.js
- blocks/site-details/renderCampaignsOverview.js
- blocks/site-details/renderSiteOverview.js
- blocks/site-details/renderSitePages.js
- scripts/auth0.js
- scripts/scripts.js
Started as just parsing User Agent, Devices and Language into human readable forms.
Continued to do this for dates everywhere and refactored admin a bit
Fix #103 
Test URLs:
- After: https://admin-improvments--eds-self-service-website--headwire-edge-delivery.aem.live/
> Human readable Dates, User Agents, Devices, Languages & Locations

- blocks/dashboard/dashboard.css
- blocks/dashboard/dashboard.js
- blocks/dashboard/renderAnalyticsTab.js
- blocks/dashboard/renderUsersTab.js
- package.json
- styles/styles.css
- moved self service site analytics into its own tab
- fixed users filter issues
Fix #116 
run locally: `aem up --no-open --url 'https://main--eds-self-service-website--headwire-edge-delivery.aem.live'`
> admin analytics tab

- blocks/dashboard/renderSiteList.js
- scripts/skeletons.js
- tour/dashboard.js
- tour/email.js
- tour/helpButton.js
Test URLs:
- After: https://<branch>--eds-self-service-website--headwire-edge-delivery.aem.live/
> Adjustments for the Tour

- blocks/wizard/wizard.js
single oninput & onchange for form, instead of per-input.
'da-' prefix for DA projects
Fix #68
> DA project slug prefix

- blocks/dashboard/renderUsersTab.js
- scripts/skeletons.js
- styles/skeletons.css
- tour/main.js
Fixes the unnecessary scroll for pagination and removes the scrollbar in the Skeleton
Test URLs:
- After: https://scrollbug--eds-self-service-website--headwire-edge-delivery.aem.live/
> Updated Skeleton and ScrollTo Fix

- blocks/dashboard/dashboard.css
- blocks/dashboard/renderAccount.js
- blocks/plans/plans.css
- blocks/plans/plans.js
- scripts/skeletons.js
Fix #127 
Test URLs:
- After: https://au--eds-self-service-website--headwire-edge-delivery.aem.live/
> add account usage

- blocks/dashboard/renderSiteList.js
- blocks/dashboard/renderUsersTab.js
- blocks/site-details/renderCampaignsAnalytics.js
- blocks/site-details/renderCampaignsAudience.js
- blocks/site-details/renderCampaignsOverview.js
- blocks/site-details/renderSettingsGeneral.js
- blocks/site-details/renderSiteOverview.js
- blocks/site-details/renderSitePages.js
- blocks/wizard/wizard.js
- scripts/scripts.js
Fixing multiple places where XXS could be exploited. Hopefully found them all
Fix #132
> fixing some XXS vulnerabilities

- blocks/dashboard/dashboard.css
- blocks/dashboard/renderUsersTab.js
Enables more Filter for the Anonymous Data, so we got a better overview over the huge Data.
> Anonymous filter

- blocks/site-details/renderCampaignsAudience.js
- blocks/site-details/renderSettingsUtils.js
- blocks/site-details/site-details.css
- scripts/scripts.js
- styles/styles.css
- tour/email.js
Fix #146 
Test URLs:
- After: https://bi--eds-self-service-website--headwire-edge-delivery.aem.live/
> add audience bulk import

- blocks/dashboard/renderAnalyticsTab.js
- blocks/dashboard/renderUsersTab.js
- blocks/email-composer/email-composer.js
- blocks/form/form.js
- blocks/site-details/renderCampaignsAudience.js
- blocks/site-details/renderCampaignsOverview.js
- blocks/site-details/renderSettingsGeneral.js
- blocks/site-details/renderSettingsUtils.js
- blocks/site-details/renderSiteOverview.js
- blocks/site-details/renderSitePages.js
- blocks/theme-editor/theme-editor.js
- libs/pagination/pagination.css
- scripts/toast.js
- styles/styles.css
- styles/toast.css
Fix #124 
Test URLs:
- After: https://toast--eds-self-service-website--headwire-edge-delivery.aem.live/
> use toast notifications

- blocks/site-details/renderCheckList.js
- blocks/site-details/renderSiteOverview.js
- blocks/site-details/renderSitePages.js
- scripts/scripts.js
- styles/styles.css
- Each tab gets it's own nav-div to avoid issues when rapidly switching tabs.
- default nav items.
- re-added await to completeChecklistItem.
- Linting
> Tabs nav fix

- blocks/site-details/renderSettingsUtils.js
- blocks/site-details/renderSiteOverview.js
- blocks/site-details/site-details.css
Fix #157 
Test URLs:
- After: https://logo--eds-self-service-website--headwire-edge-delivery.aem.live/
> add logo to site overview

- blocks/site-details/renderSitePages.js
Fix #175
Test URLs:
- After: https://pagesfix--eds-self-service-website--headwire-edge-delivery.aem.live/
> Hide Preview or Live links based on status 

- blocks/dashboard/dashboard.css
- blocks/dashboard/renderSiteList.js
- blocks/site-details/renderCampaignsAudience.js
- blocks/site-details/renderCampaignsOverview.js
- blocks/site-details/renderSettingsGeneral.js
- blocks/site-details/renderSettingsUtils.js
- blocks/site-details/renderSitePages.js
- styles/styles.css
fixed DA site list not loading on initial login
Fix #182
> fixed DA site list not loading on initial login

- blocks/site-details/renderSitePages.js
> Draft page list never has published badge

- blocks/site-details/renderSitePages.js
> fixed index pages not having "/index" be omitted from links

- blocks/email-composer/email-composer.js
- blocks/site-details/renderCampaignsAnalytics.js
- blocks/site-details/renderCampaignsOverview.js
- blocks/site-details/renderSitePages.js
- scripts/scripts.js
changed email paths to go to server now that worker code was moved
> New email preview location

- blocks/dashboard/renderUsersTab.js
- blocks/site-details/site-details.js
- styles/toast.css
Fixes an issue where it sometimes crashes due to excessive data loading.
With maxRows Query Params, we can also speed up the tests if we only load 100 entries instead of the default of 10000.
Test URLs:
- After: https://admin-users-fix--eds-self-service-website--headwire-edge-delivery.aem.live/
> Admin users fix

- blocks/site-details/renderCheckList.js
- blocks/site-details/renderSiteSEO.js
- blocks/site-details/site-details.js
- scripts/scripts.js
- styles/styles.css
Checklist & updates fixes based on issues found while creating test.
SEO tab classes for tests
> Checklist updates

- blocks/site-details/renderSiteSpreadsheets.js
- blocks/site-details/site-details.css
- blocks/site-details/site-details.js
- icons/sheets.svg
- scripts/scripts.js
- scripts/skeletons.js
- scripts/utils.js
- styles/styles.css
- tour/main.js
- tour/site.js
Added the functionalities to edit a spreadsheet inside our app insted of editing it in Google Drive.
(Does not work for Dark Alley)
Needs this [Backend Changes](https://github.com/headwire-edge-delivery/eds-self-service-scripts/pull/81)
Test URLs:
- After: https://SheetEditor--eds-self-service-website--headwire-edge-delivery.aem.live/
> Added a Sheet Editor

- tour/generateTour.js
- tour/main.js
- tour/seo.js
Fix #209
Test URLs:
- After: https://dialogTourIssue--eds-self-service-website--headwire-edge-delivery.aem.live/
> Waiting for the Update Dialog to be closed before show Auto Tour

- tour/main.js
Test URLs:
- After: https://noDialog--eds-self-service-website--headwire-edge-delivery.aem.live/
> Check if a Dialog exists, if it's closed or not

- blocks/site-details/renderSiteOverview.js
- blocks/site-details/renderSitePages.js
- blocks/wizard/wizard.css
- blocks/wizard/wizard.js
- head.html
- package-lock.json
- package.json
- scripts/analytics.js
- scripts/auth0.js
- tour/homepage.js
- tour/seo.js
- tour/site.js
- tour/templates.js
Test URLs:
- After: https://ui--eds-self-service-website--headwire-edge-delivery.aem.live/
> Updates for better onboarding

- blocks/wizard/wizard.js
no longer chooses template based on '.is-selected' class, and no longer sets first item as selected. Instead checks url to choose pre-selected template, otherwise null.
This fixes issue where create button would always result in a wknd template project. This is a bit hacky, but anything more requires a big refactor
> wrong template fix

- blocks/account-settings/account-settings.js
- blocks/dashboard/renderUsersTab.js
- blocks/email-composer/email-composer.js
- blocks/form/form.js
- blocks/site-details/renderCampaignsAudience.js
- blocks/site-details/renderCampaignsOverview.js
- blocks/site-details/renderCheckList.js
- blocks/site-details/renderSettingsGeneral.js
- blocks/site-details/renderSettingsUtils.js
- blocks/site-details/renderSitePages.js
- blocks/site-details/renderSiteSpreadsheets.js
- blocks/site-details/site-details.js
- blocks/theme-editor/theme-editor.js
- package-lock.json
- package.json
- scripts/dialogs.js
- scripts/toast.js
- scripts/utils.js
Fix #227
Test URLs:
- After: https://errors--eds-self-service-website--headwire-edge-delivery.aem.live/
> Updated Error Messages and Bug fixes

- blocks/theme-editor/baseBlockHtml.js
- blocks/theme-editor/theme-editor.css
- blocks/theme-editor/theme-editor.js
- package-lock.json
- package.json
- scripts/scripts.js
Test URLs:
- After: https://themeeditor--eds-self-service-website--headwire-edge-delivery.aem.live/
> Improved Theme Editor

- blocks/theme-editor/theme-editor.js
- package-lock.json
- package.json
Test URLs:
- After: https://zoom--eds-self-service-website--headwire-edge-delivery.aem.live/
> Fix for Sports Template Zooming
